# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swash_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('confirmed', 'confirmed'), ('paid', 'paid'), ('pickup', 'pickup'), ('progress', 'progress'), ('packing', 'packing'), ('on_the_way', 'on_the_way'), ('delivered', 'delivered'), ('pending', 'pending'), ('cancel', 'cancel')], default='draft', max_length=20, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='swash_order.Order', verbose_name='order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='swash_service.Service', verbose_name='services')),
            ],
            options={
                'verbose_name': 'order_service',
                'verbose_name_plural': 'order_services',
                'db_table': 'order_services',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('confirmed', 'confirmed'), ('paid', 'paid'), ('pickup', 'pickup'), ('progress', 'progress'), ('packing', 'packing'), ('on_the_way', 'on_the_way'), ('delivered', 'delivered'), ('pending', 'pending'), ('cancel', 'cancel')], default='draft', max_length=20, verbose_name='status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='swash_order.Order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order_status',
                'verbose_name_plural': 'order_states',
                'db_table': 'order_states',
            },
        ),
    ]
