# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swash_service', '0001_initial'),
        ('swash_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('lat', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='lat')),
                ('long', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='long')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('status', models.CharField(choices=[('pickup', 'pickup'), ('delivery', 'delivery')], default='pickup', max_length=10, verbose_name='status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='swash_order.Order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'addresses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='orderservice',
            unique_together=set([('order', 'service')]),
        ),
        migrations.AlterUniqueTogether(
            name='orderaddress',
            unique_together=set([('order', 'status')]),
        ),
    ]
