# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swash_order', '0002_auto_20180928_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('paid', 'paid'), ('pickup', 'pickup'), ('progress', 'progress'), ('packing', 'packing'), ('on_the_way', 'on_the_way'), ('delivered', 'delivered'), ('pending', 'pending'), ('cancel', 'cancel')], default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='swash_order.Order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='swash_service.Service', verbose_name='services'),
        ),
    ]
