# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swash_order', '0003_auto_20180928_1128'),
        ('swash_order', '0003_auto_20180928_1252'),
    ]

    operations = [
    ]
