# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swash_order', '0004_merge_20180928_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='lat'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='long',
            field=models.FloatField(default=0.0, verbose_name='long'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('paid', 'paid'), ('pickup', 'pickup'), ('progress', 'progress'), ('packing', 'packing'), ('on_the_way', 'on_the_way'), ('delivered', 'delivered'), ('pending', 'pending'), ('cancel', 'cancel')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
