# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swash_order', '0005_auto_20180928_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(null=True, verbose_name='pickup date'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='status',
            field=models.CharField(choices=[('pickup', 'pickup'), ('delivery', 'delivery'), ('alternative', 'alternative')], default='pickup', max_length=10, verbose_name='status'),
        ),
    ]
