# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swash_order', '0006_auto_20180930_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('paid', 'paid'), ('pickup', 'pickup'), ('progress', 'progress'), ('packing', 'packing'), ('on_the_way', 'on_the_way'), ('delivered', 'delivered'), ('pending', 'pending'), ('cancel', 'cancel'), ('pickedup', 'pickedup')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
