# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swash_order', '0011_auto_20181001_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='end_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='pickup_date',
            field=models.DateField(null=True, verbose_name='pickup date'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='start_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
