# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swash_order', '0012_auto_20181003_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='pickup_date',
            new_name='selected_date',
        ),
    ]
