# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.ImageField(upload_to='category_icon', verbose_name='icon')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='discount')),
                ('notification', models.CharField(blank=True, max_length=250, null=True, verbose_name='notification')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='swash_service.Category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.ImageField(upload_to='service_icon', verbose_name='icon')),
                ('notification', models.CharField(blank=True, max_length=250, null=True, verbose_name='notification')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='discount')),
                ('duration', models.DateField(blank=True, null=True, verbose_name='duration')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='swash_service.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'services',
            },
        ),
    ]
