# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 20:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swash_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('start_time', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)], verbose_name='start time')),
                ('end_time', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)], verbose_name='end time')),
            ],
            options={
                'verbose_name': 'period_time',
                'verbose_name_plural': 'period_times',
                'db_table': 'period_times',
            },
        ),
    ]
