# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_data', '0003_auto_20180909_0938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('user', 'account_type', 'account_id')]),
        ),
    ]
