# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_auto_20180914_0252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('account_type', 'account_id')]),
        ),
    ]
