# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0008_auto_20180914_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('verification_code', models.CharField(blank=True, max_length=5, verbose_name='verification code')),
                ('expired', models.BooleanField(default=False, verbose_name='expired')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='mobile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sur_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='verificationmobile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='user_data.Profile', verbose_name='profile'),
        ),
    ]
