# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0009_auto_20180924_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_verified',
            field=models.BooleanField(default=False, verbose_name='mobile_verified'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile', verbose_name='profile avatar'),
        ),
    ]
