# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0012_auto_20181002_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=20, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='mobile number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_verified',
            field=models.BooleanField(default=False, verbose_name='mobile verified'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6, verbose_name='sex'),
        ),
    ]
