# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0013_auto_20181004_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('verification_code', models.CharField(blank=True, max_length=8, verbose_name='verification code')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='user_data.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'verification',
                'verbose_name_plural': 'verification',
                'db_table': 'verification',
            },
        ),
    ]
