# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swash_order', '0014_auto_20181003_1501'),
        ('user_data', '0014_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('department', models.CharField(choices=[('payment', 'payment'), ('technical', 'technical')], default='payment', max_length=40, verbose_name='department')),
                ('persiority', models.CharField(choices=[('normal', 'normal'), ('hight', 'hight'), ('urgent', 'urgent')], default='normal', max_length=40, verbose_name='persiority')),
                ('state', models.CharField(choices=[('open', 'open'), ('unread_department', 'unread_department'), ('unread_user', 'unread_user'), ('close', 'close')], default='open', max_length=40, verbose_name='state')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='swash_order.Order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('status', models.CharField(max_length=30, verbose_name='status')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='user_data.Ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket_history',
                'verbose_name_plural': 'ticket_histories',
                'db_table': 'ticket_history',
            },
        ),
    ]
